version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      ENABLE_IPV6: 'true'
      DEFAULT_HOST: 'staging.sophox.org'

  whoami:
    image: jwilder/whoami
    environment:
      VIRTUAL_HOST: 'whoami.staging.sophox.org'
