version: '2.3'

services:

  osm2pgsql-import:
    # Parse osm file into Postgres DB, and continuously update from live OSM data
    image: sophox/osm2pgsql_osmium
    volumes:
      - "${DOWNLOAD_DIR}:/downloads:rw"              # downloaded planet file
      - "${OSM_PGSQL_DATA_DIR}:/osm-pgsql:rw"
      - "${OSM_PGSQL_TEMP_DIR}:/osm-pgsql-temp:rw"
      - "${REPO_DIR}/osm-to-pgsql:/osm-to-pgsql:ro"  # source code
      - "${STATUS_DIR}:/app-status:rw"               # status files (e.g. file.downloaded)
    environment:
      FLAG_PG_IMPORTED: "/app-status/osm-pgsql.imported"
      IS_FULL_PLANET: "${IS_FULL_PLANET}"
      OSM_FILE_PATH: "/downloads/${OSM_FILE}"
      OSM_PGSQL_CODE: "/osm-to-pgsql"
      OSM_PGSQL_CPU_IMPORT: 4
      OSM_PGSQL_DATA: "/osm-pgsql"
      OSM_PGSQL_MEM_IMPORT: "${MEM_OSM_PGSQL_IMPORT_MB}"
      OSM_PGSQL_TEMP: "/osm-pgsql-temp"
      POSTGRES_DB: gis
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD:
      POSTGRES_USER: sophox
    command: /osm-to-pgsql/osm2pgsql-import.sh
    networks:
      - postgres_net
    logging:
      driver: json-file
      options: {max-file: "3", max-size: "10m"}

networks:
  postgres_net:
