version: '2.3'

services:

  osm2rdf-relloc:
    # This container continuously updates relation's center points
    # by averaging all member's center points (not very accurate)
    image: sophox/osm2rdf
    working_dir: "/app-osm2rdf"
    command: "./osm2rdf-relloc.sh"
    restart: on-failure
    volumes:
      - "${OSM_RDF_DATA_DIR}:/osm-rdf:rw"
      - "${REPO_DIR}/osm2rdf:/app-osm2rdf:ro"
      - "${STATUS_DIR}:/app-status:ro"
    environment:
      FLAG_TTL_IMPORTED: "/app-status/osm-rdf.imported"
      IS_FULL_PLANET: "${IS_FULL_PLANET}"
      OSM_RDF_DATA: "/osm-rdf"
      BLAZEGRAPH_URL: "${BLAZEGRAPH_URL}"
    networks:
      - blazegraph_net
    logging:
      driver: json-file
      options: {max-file: "3", max-size: "10m"}

networks:
  blazegraph_net:
