version: '2.3'

services:

  osm2rdf-update:
    # This container continuously updates from OSM data to Blazegraph
    build: "${BUILD_DIR}/osm2rdf"
    working_dir: "/app-osm2rdf"
    command: "./osm2rdf-update.sh"
    # restart: on-failure
    volumes:
      - "${OSM_RDF_DATA_DIR}:/osm-rdf:rw"
      - "${REPO_DIR}/osm2rdf:/app-osm2rdf:ro"
      - "${STATUS_DIR}:/app-status:rw"
    environment:
      FLAG_TTL_IMPORTED: "/app-status/osm-rdf.imported"
      IS_FULL_PLANET: "${IS_FULL_PLANET}"
      MAX_DOWNLOAD: 5120
      OSM_RDF_DATA: "/osm-rdf"
      BLAZEGRAPH_URL: "${BLAZEGRAPH_URL}"
      UPDATE_URL: "https://planet.openstreetmap.org/replication/minute"
    networks:
      - blazegraph_net
    logging:
      driver: json-file
      options: {max-file: "3", max-size: "10m"}

networks:
  blazegraph_net:
