version: '2.2'

services:

#  traefik:
#    image: traefik
#    restart: always
#    ports:
#      - "80:80"
#      - "443:443"
#      - "127.0.0.1:8080:8080"
#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock:ro"
#      - "${REPO_DIR}/docker/traefik.toml:/traefik.toml:ro"
#      - "${ACME_FILE}:/acme.json:rw"
#    container_name: traefik

  postgres-updater:
    image: sophox/osm2pgsql_osmium
    command: /osm-to-pgsql/osm-to-pgsql.sh
    volumes:
    - "${REPO_DIR}/osm-to-pgsql:/osm-to-pgsql:ro"
    - "${DOWNLOAD_DIR}:/downloads:ro"
    - "${OSM_PGSQL_DATA_DIR}:/osm-pgsql:rw"
    - "${OSM_PGSQL_TEMP_DIR}:/osm-pgsql-temp:rw"
    environment:
      OSM_FILE_PATH: "/downloads/${OSM_FILE}"
      POSTGRES_HOST: postgres
      POSTGRES_DB: gis
      POSTGRES_USER: sophox
      POSTGRES_PASSWORD:
      OSM_PGSQL_DATA: "/osm-pgsql"
      OSM_PGSQL_TEMP: "/osm-pgsql-temp"
      OSM_PGSQL_CODE: "/osm-to-pgsql"
      # MEM is a percentage of total machine memory
      OSM_PGSQL_MEM_IMPORT: 30
      OSM_PGSQL_CPU_IMPORT: 3
      OSM_PGSQL_MEM_UPDATE: 10
      OSM_PGSQL_CPU_UPDATE: 2
      LOOP_SLEEP: 60
    networks:
    - postgres_conn
    depends_on:
    - postgres

#  osm-to-rdf:
#    build: "${BUILD_DIR}/osm2rdf"
#    mem_limit: "${OSM_RDF_MEM_MB:-4000}m"
#    memswap_limit: "${OSM_RDF_MEM_MB:-4000}m"
#    mem_swappiness: 0
#    volumes:
#    - "${DOWNLOAD_DIR}:/downloads:ro"
#    - "${OSM_RDF_DATA_DIR}:/osm-rdf:rw"
#    - "${OSM_RDF_TEMP_DIR}:/osm-rdf-temp:rw"
#    environment:
#      OSM_FILE_PATH: "/downloads/${OSM_FILE}"
#      OSM_RDF_DATA: "/osm-rdf"
#      OSM_RDF_TEMP: "/osm-rdf-temp"
#      OSM_RDF_WORKERS: 2

#    networks:
#    - blazegraph_conn
#    depends_on:
#    - blazegraph

  osm-regions:
    build: "${BUILD_DIR}/osm-regions-server"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: gis
      POSTGRES_USER: sophox
      POSTGRES_PASSWORD:
      SOPHOX_URL: "http://blazegraph:9999/bigdata/sparql"
      WIKIBASE_URL: "https://wikibase.org/bigdata/namespace/wdq/sparql"
      REGIONS_TABLE: planet_osm_polygon
    ports:
    - "9978"
    networks:
    - postgres_conn
    - blazegraph_conn
    depends_on:
    - postgres
    - blazegraph
    labels:
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:staging.sophox.org;PathPrefixStrip:/regions/"
#    - "traefik.port=80"

  vote-server:
    build: "${BUILD_DIR}/vote-server"
    environment:
      SOPHOX_URL: "http://blazegraph:9999/bigdata/sparql"
    ports:
    - "9979"
    networks:
    - blazegraph_conn
    depends_on:
    - blazegraph
    labels:
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:staging.sophox.org;PathPrefixStrip:/store/"
#    - "traefik.port=80"


  #  sophox-gui:
  #    build: https://github.com/nickpeihl/wikidata-query-gui.git#dockerize
  #    ports:
  #      - "80"
  #    labels:
  #      - "traefik.enable=true"
  #      - "traefik.frontend.rule=Host:staging.sophox.org"

  #  mapshaper:
  #    image: crazycapivara/docker-mapshaper
  #    ports:
  #      - "5555"
  #    labels:
  #      - "traefik.enable=true"
  #      - "traefik.frontend.rule=Host:staging.sophox.org;PathPrefixStrip:/mapshaper/"


  postgres:
    image: "openmaptiles/postgis:2.9"
    command: >-
      postgres
      -c 'shared_buffers = 4GB'
      -c 'work_mem = 1GB'
      -c 'maintenance_work_mem = 4GB'
      -c 'effective_io_concurrency = 500'
      -c 'max_worker_processes = 5'
      -c 'max_parallel_workers_per_gather = 2'
      -c 'max_parallel_workers = 5'
      -c 'checkpoint_timeout = 1h'
      -c 'max_wal_size = 5GB'
      -c 'min_wal_size = 1GB'
      -c 'checkpoint_completion_target = 0.9'
      -c 'random_page_cost = 1.1'
      -c 'min_parallel_table_scan_size = 8MB'
      -c 'min_parallel_index_scan_size = 512kB'
      -c 'effective_cache_size = 6GB'
    volumes:
      - "${DATA_DIR}/postgres:/var/lib/postgresql/data:rw"
    networks:
      - postgres_conn
    ports:
      - "5432"
    environment:
      POSTGRES_DB: gis
      POSTGRES_USER: sophox
      POSTGRES_PASSWORD:

  blazegraph:
    # placeholder
    image: busybox
    command: sleep 10000d
    ports:
    - "9999"
    volumes:
    - "${DATA_DIR}/blazegraph:/app/data:rw"
    networks:
    - blazegraph_conn

networks:
  postgres_conn:
  blazegraph_conn:
