debug = true
logLevel = "DEBUG"
defaultEntryPoints = ["https","http"]

[entryPoints]
    [entryPoints.http]
        address = ":80"
    [entryPoints.https]
        address = ":443"
        [entryPoints.https.tls]

[docker]
    endpoint = "unix:///var/run/docker.sock"
    # domain = "staging.sophox.org"
    watch = true
    exposedByDefault = false

[api]
    debug = true

[traefikLog]
[accessLog]
