debug = true
#logLevel = "DEBUG"
logLevel = "INFO"
defaultEntryPoints = ["https","http"]

[entryPoints]
    [entryPoints.http]
        address = ":80"
    [entryPoints.https]
        address = ":443"
        [entryPoints.https.tls]

[docker]
    endpoint = "unix:///var/run/docker.sock"
    watch = true
    exposedByDefault = false

[api]
#    debug = true

[traefikLog]
[accessLog]
